### ISSUE TITLE
Research Blueprint-cloud-messaging

### ISSUE THREAD

**Issue by DannyPeck** [CS450-ECE461/fall2016-group2-apiserver#14]
Blueprint-cloud-messaging is a Blueprint module created by Dr. Hill for sending messages.  It supports all of the messaging functionality needed to implement our system.  We need to figure out how it works, how to use it, how to integrate it into a Blueprint application, and where within our architecture it is supposed to be defined.

Here is a link to [blueprint-cloud-messaging](https://github.com/onehilltech/blueprint-cloud-messaging)

Findings should be documented in a wiki page explaining your findings.

**Comment by cotz1995** [comment]
We will not be using blueprint-cloud messaging. It used Gatekeeper Auth and Google Cloud Messaging. Both of which are far to involved for the scope of this project. Thus, we will have to create our own system for messaging.
