### ISSUE TITLE
Integrate Coveralls for code coverage metrics

### ISSUE THREAD

**Issue by najowhit** [CS450-ECE461/fall2016-group2-apiserver#20]
We need to integrate coveralls into our TravisCI build. 

At a high level, we need to add the dependency and script into package.json and then add the script to .travis.yml. 

The [documentation](https://coveralls.zendesk.com/hc/en-us) is a great starting point.

**Comment by DannyPeck** [comment]
We should also look into adding the code coverage badge to our Github Readme.

**Comment by najowhit** [comment]
Merged.
