### ISSUE TITLE
Create a new Admin account when a new organization is created

### ISSUE THREAD

**Issue by DannyPeck** [CS450-ECE461/fall2016-group2-apiserver#24]
When a new organization is created it will emit a 'organization.created' event.  Using Blueprints listeners we can create a listener for the 'organization.created' event called createAdmin which will take in the organization as a parameter and create and add the admin to the database.

**Comment by amjustin13** [comment]
Refactored test to implement the user email, added nodemailer capabilities and also refactored test to implement nodemailer stub.
