### ISSUE TITLE
Research AWS and how to host our instances

### ISSUE THREAD

**Issue by DannyPeck** [CS450-ECE461/fall2016-group2-apiserver#28]
We need to figure out how to create instances (virtual machines) in aws and put our services on these instances.

**Comment by cotz1995** [comment]
Successfully created a new AWS ubuntu instance and got the current development code running. The dev server can be reached at http://ec2-35-163-81-202.us-west-2.compute.amazonaws.com:5000/. The prod server will eventually be at http://ec2-35-163-81-202.us-west-2.compute.amazonaws.com/
