### ISSUE TITLE
Define User Model

### ISSUE THREAD

**Issue by DannyPeck** [CS450-ECE461/fall2016-group2-apiserver#3]
We need to define the model of a User within our blueprint application.  This will be the schema for what attributes Users will have and using this model, will allow us to directly interact with the MongoDB database.  This is achieved via a Node module called Mongoose.js which is a module for using Javascript to interact with mongodb.  This module is integrated directly into Blueprint via the blueprint-mongodb module.

Note: The user model is subject to change based on requirements and this is a rough guess.
# User
| attributes | types  |
|-----------|-------|
| user_id     | String |
| org_id       | String |
| email        | String |
| username | String |
| password | String |
| job_title   | String |

**Comment by eburgun** [comment]
We also probably want some sort identifier for admin status. Could use a boolean to keep it simple. Also, if you're dead set on the SuperAdmin you'd need one for that as well.

**Comment by DannyPeck** [comment]
So, after receiving the answers to our questions from Dr. Hill, we need to rethink the Admin portion as there is only going to be one Admin.
